/**
 * Example: Large collections
 * ---------------------------
 * Patterns that stay fast as data grows: chunked bulk inserts, index-backed
 * range queries, and keyset pagination that's O(pageSize) at any depth. The
 * demo seeds 50,000 rows.
 */
import { openDatabase, type Database, type Schema } from 'idbkit';

export interface Event {
  id: number; // auto-increment
  type: 'click' | 'view' | 'purchase';
  amount: number;
  timestamp: number;
}

interface EventsDB extends Schema {
  events: {
    key: number;
    value: Event;
    indexes: {
      byTimestamp: number;
      byType: string;
    };
  };
}

export async function openEventsDB(name = 'example-events'): Promise<Database<EventsDB>> {
  return openDatabase<EventsDB>({
    name,
    version: 1,
    stores: {
      events: {
        keyPath: 'id',
        autoIncrement: true,
        indexes: {
          byTimestamp: { keyPath: 'timestamp' },
          byType: { keyPath: 'type' },
        },
      },
    },
  });
}

/**
 * Insert many records efficiently. Each chunk is one transaction; chunking keeps
 * memory bounded for very large imports.
 */
export async function seedEvents(
  db: Database<EventsDB>,
  total: number,
  chunkSize = 5_000,
): Promise<void> {
  const types: Event['type'][] = ['click', 'view', 'purchase'];
  const base = Date.now() - total * 1000;
  for (let start = 0; start < total; start += chunkSize) {
    const end = Math.min(start + chunkSize, total);
    const batch: Omit<Event, 'id'>[] = [];
    for (let i = start; i < end; i++) {
      batch.push({
        type: types[i % types.length],
        amount: i % 7,
        timestamp: base + i * 1000,
      });
    }
    // Out-of-line/auto-increment keys are generated by the store.
    await db.store('events').bulkAdd(batch as Event[]);
  }
}

/** Count by an indexed field without scanning values. */
export function countByType(db: Database<EventsDB>, type: Event['type']): Promise<number> {
  return db.store('events').index('byType').count(type);
}

/** Events within a time window, using the timestamp index (no full scan). */
export function eventsBetween(
  db: Database<EventsDB>,
  fromMs: number,
  toMs: number,
): Promise<Event[]> {
  return db.store('events').query().index('byTimestamp').between(fromMs, toMs).toArray();
}

/**
 * Walk the entire collection in pages without ever skipping records. Paginating
 * by the primary key keeps each page exact and cheap.
 */
export async function* paginateAll(
  db: Database<EventsDB>,
  pageSize = 1_000,
): AsyncGenerator<Event[]> {
  let after: number | undefined;
  for (;;) {
    const page = await db.store('events').paginateKeyset({ pageSize, after });
    if (page.items.length === 0) return;
    yield page.items;
    if (!page.hasMore || page.cursor == null) return;
    after = page.cursor;
  }
}

// Demo when run directly.
if (import.meta.url === `file://${process.argv[1]}`) {
  const run = async () => {
    const db = await openEventsDB(`example-events-${Date.now()}`);

    const TOTAL = 50_000;
    const t0 = Date.now();
    await seedEvents(db, TOTAL);
    console.log(`Inserted ${TOTAL.toLocaleString()} events in ${Date.now() - t0}ms`);

    console.log('Total count:', await db.store('events').count());
    console.log('Purchases:', await countByType(db, 'purchase'));

    const windowStart = Date.now() - 5000 * 1000;
    const t1 = Date.now();
    const recent = await eventsBetween(db, windowStart, Date.now());
    console.log(`Indexed range query → ${recent.length} rows in ${Date.now() - t1}ms`);

    // Keyset pagination is O(pageSize) per page in a real browser (the cursor
    // seeks straight to `after`). The Node polyfill rescans from the start on
    // each cursor open, so we only demo the first few pages here; `paginateAll`
    // walks the whole collection efficiently in the browser.
    let pages = 0;
    let seen = 0;
    let after: number | undefined;
    const t2 = Date.now();
    while (pages < 3) {
      const page = await db.store('events').paginateKeyset({ pageSize: 5_000, after });
      pages += 1;
      seen += page.items.length;
      if (!page.hasMore || page.cursor == null) break;
      after = page.cursor;
    }
    console.log(`Keyset-paged first ${seen.toLocaleString()} rows in ${pages} pages (${Date.now() - t2}ms)`);

    await db.delete();
  };
  run().catch((e) => {
    console.error(e);
    process.exit(1);
  });
}
